name = "rolldorado-bet-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-bet.cz"
HMAC_KEY = "6b29f16ca841c8fa831a1d908c2909c483ddcad325bccfbbd64f37c9c11a268a"
COOKIE_NAME = "jf9"
PLAY_PATH = "start"
BUTTON_ID = "pa766483b39cbd9c9e9003813f6bd9313"
GATE_SALT = "c71ccb55fc0bbe1f"
