name = "rolldorado-bet-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-bet.cz"
HMAC_KEY = "6b29f16ca841c8fa831a1d908c2909c483ddcad325bccfbbd64f37c9c11a268a"
COOKIE_NAME = "6gh"
PLAY_PATH = "play-now"
BUTTON_ID = "pa766483b39cbd9c9e9003813f6bd9313"
GATE_SALT = "190526d9ad261c60"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "0sd8"
CTA_SELECTOR = ".play-button"
